### ISSUE TITLE
Can't yarn test:unit -u

### ISSUE THREAD

**Issue by aifedespaix** [jean-smaug/condorcet#110]
Can't yarn test:unit -u
node 12.6 and 10

> yarn run v1.17.3
> $ vue-cli-service test:unit -u
> FAIL src/store/modules/__tests__/app.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\store\modules\__tests__\app.spec.js:5
>     import { createLocalVue } from "@vue/test-utils";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/views/__tests__/Poll.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\views\__tests__\Poll.spec.js:7
>     import { shallowMount, createLocalVue } from "@vue/test-utils";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/views/__tests__/PublicPolls.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\views\__tests__\PublicPolls.spec.js:5
>     import { shallowMount, createLocalVue } from "@vue/test-utils";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/utils/__tests__/initialization.spec.js
>   ● Test suite failed to run
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\utils\__tests__\initialization.spec.js:5
>     import initialization from "../initialization";const store = {
>            ^^^^^^^^^^^^^^
> 
>     SyntaxError: Unexpected identifier
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/views/__tests__/PollResult.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\views\__tests__\PollResult.spec.js:5
>     import { shallowMount } from "@vue/test-utils";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/utils/__tests__/request.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\utils\__tests__\request.spec.js:5
>     import { createPoll, createVote } from "../request";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/store/modules/__tests__/user.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\store\modules\__tests__\user.spec.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { createLocalVue } from "@vue/test-utils";
>                                                                                                     ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/views/__tests__/Authentication.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\views\__tests__\Authentication.spec.js:5
>     import { shallowMount, createLocalVue } from "@vue/test-utils";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> PASS functions/utils/__tests__/uninominal.spec.js
> FAIL src/utils/__tests__/authentication.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\utils\__tests__\authentication.spec.js:5
>     import { auth } from "../../firebase";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/store/modules/__tests__/poll.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\store\modules\__tests__\poll.spec.js:6
>     import { createLocalVue } from "@vue/test-utils";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/views/__tests__/PollsList.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\views\__tests__\PollsList.spec.js:5
>     import { shallowMount, createLocalVue } from "@vue/test-utils";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/views/__tests__/PollCreation.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\views\__tests__\PollCreation.spec.js:7
>     import { shallowMount, createLocalVue } from "@vue/test-utils";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/components/__tests__/Notifications.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\components\__tests__\Notifications.spec.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { shallowMount } from "@vue/test-utils";
>                                                                                                     ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/components/__tests__/Loader.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\components\__tests__\Loader.spec.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { shallowMount } from "@vue/test-utils";
>                                                                                                     ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/components/__tests__/Navbar.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\components\__tests__\Navbar.spec.js:5
>     import { shallowMount, createLocalVue } from "@vue/test-utils";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/components/__tests__/Card.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\components\__tests__\Card.spec.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { shallowMount } from "@vue/test-utils";
>                                                                                                     ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL functions/utils/__tests__/condorcet-v3.spec.js
>   ● Test suite failed to run
> 
>     Cannot find module 'merge-objects-values' from 'condorcet-v3.js'
> 
>     > 1 | const mergeObjectsValues = require("merge-objects-values");
>         |                                                       ^
>       2 | 
>       3 | const getMatrixOfTheDuelsForOneVote = ranking => {
>       4 |   const rankingMatrix = ranking.reduce((secondAcc, answer) => {
> 
>       at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
>       at Object.<anonymous> (functions/utils/condorcet-v3.js:1:55)
> 
> FAIL src/__tests__/App.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\__tests__\App.spec.js:1
>     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { shallowMount, createLocalVue } from "@vue/test-utils";
>                                                                                                     ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> FAIL src/views/__tests__/PollJoin.spec.js
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     C:\Users\aife\IdeaProjects\condorcet\src\views\__tests__\PollJoin.spec.js:5
>     import { shallowMount, createLocalVue } from "@vue/test-utils";
>            ^
> 
>     SyntaxError: Unexpected token {
> 
>       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
> 
> Test Suites: 19 failed, 1 passed, 20 total
> Tests:       1 passed, 1 total
> Snapshots:   1 passed, 1 total
> Time:        3.158s
> Ran all test suites.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>

**Comment by jean-smaug** [comment]
Pour ce test la il faut que tu ailles dans le dossiers function et que tu fasse un `yarn install`. J'ai zappé de le mettre dans le setup 😅 


```
FAIL functions/utils/tests/condorcet-v3.spec.js
● Test suite failed to run

Cannot find module 'merge-objects-values' from 'condorcet-v3.js'

 1 | const mergeObjectsValues = require("merge-objects-values");
    |                                                       ^
  2 | 
  3 | const getMatrixOfTheDuelsForOneVote = ranking => {
  4 |   const rankingMatrix = ranking.reduce((secondAcc, answer) => {

  at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
  at Object.<anonymous> (functions/utils/condorcet-v3.js:1:55)
```
